services:
  frontend:
    build: ./frontend
    ports:
      - "5173:3000"
    container_name: frontend
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    command: npm run dev

  backend:
    build: ./backend
    tty: true
    container_name: communication_tool_backend
    volumes:
      - ./backend:/app
    ports:
      - "5050:80"

volumes:
  frontend_node_modules:
