name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "latest"
      - name: Install dependencies and build test
        run: |
          cd ./frontend
          npm ci
          npm run build
  format-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "latest"
      - name: Install dependencies
        run: |
          cd ./frontend
          npm ci
      - name: Run Eslint
        run: |
          cd ./frontend
          npm run lint:ci
      - name: Run Prettier
        run: |
          cd ./frontend
          npm run fmt:ci
