name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "latest"
      - name: Install dependencies and build test
        run: |
          cd ./frontend
          npm ci
          npm run build
  format-check-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "latest"
      - name: Install dependencies
        run: |
          cd ./frontend
          npm ci
      - name: Run Eslint
        run: |
          cd ./frontend
          npm run lint:ci
      - name: Run Prettier
        run: |
          cd ./frontend
          npm run fmt:ci
  format-check-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          cd ./backend
          pip install poetry
          poetry install
      - name: Run Black
        run: |
          cd ./backend
          poetry run black --check main.py
      - name: Run Pylint
        run: |
          cd ./backend
          poetry run pylint main.py
